image: node:20.11.1

stages:
  - setup
  - test
  - unit-test

install:
  stage: setup
  script: npm ci

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

unit:
  stage: unit-test
  script:
    - npm ci
    - npm run test